// <auto-generated />
using Afterpelago.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Afterpelago.Data.Migrations
{
    [DbContext(typeof(AfterpelagoDbContext))]
    [Migration("20261006020714_AddAccessRecords")]
    partial class AddAccessRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Afterpelago.Domain.AccessRecord", b =>
                {
                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.HasIndex("Status");

                    b.ToTable("AccessRecords");
                });

            modelBuilder.Entity("Afterpelago.Domain.DemoCounter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DemoCounters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedAt = "2026-01-01T00:00:00.0000000Z",
                            Value = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
